version: "2"
services:
  #This is for test
  # base_pwn:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: ctftraining/base_pwn_xinetd_kafel_1804

  pwn:
    build:
      context: .
      dockerfile: example.Dockerfile # Your Dockerfile
    # image: ctftraining/pwn_kafel_test # This is for test, you can change this name
    volumes:
      - ./tcpdump:/var/lib/tcpdump # Tcp dump dir
    ports:
      - "10001:10000" # Must sync with pwn.xinetd.conf
    environment:
      - FLAG=minilctf{base_pwn_xinetd_kafel} # flag init
      - TCPDUMP_ENABLE=1
    # depends_on:
    #   - base_pwn
